In [13]:
### sentences
sentences=['the glass of milk',  
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]
sentences#This is basically a list of sentences a paragraph having list of senetences

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [14]:
"""Define vocabulary size"""
voc_size=10000


In [15]:
#One Hot representation
from tensorflow.keras.preprocessing.text import one_hot
one_hot_rep=[one_hot(sentence,voc_size) for sentence in sentences]
one_hot_rep
#This will convert all sentence into some vector but each sentence can have different number of vector components,diff dimensions 
#but all sentence should have  equal number of vector components for easier training of model

[[6764, 8385, 1216, 8467],
 [6764, 8385, 1216, 4976],
 [6764, 9414, 1216, 2639],
 [5147, 2160, 4341, 6044, 5477],
 [5147, 2160, 4341, 6044, 7353],
 [5937, 6764, 4754, 1216, 8025],
 [7845, 8728, 6685, 6044]]

In [16]:
from tensorflow.keras.layers import Embedding
#prev in ANN we used thensorflow.keras.layers to import dense here we will import the embedding layer and simpleRNN layer layer later
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [17]:
sent_length=0
for sentence in sentences:
    count=len(sentence.split())
    sent_length=max(sent_length,count)
print(sent_length)
#want to find max number of words in each sentence so split each sentence into array of words and compare its len
#This will give max_len and we can also set the maxlen to any value>= this value obtained acc to our wish

5


In [18]:
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)#pre means will add zeros at the beginning to match the max length wheerever required
print(embedded_docs)


[[   0 6764 8385 1216 8467]
 [   0 6764 8385 1216 4976]
 [   0 6764 9414 1216 2639]
 [5147 2160 4341 6044 5477]
 [5147 2160 4341 6044 7353]
 [5937 6764 4754 1216 8025]
 [   0 7845 8728 6685 6044]]


In [19]:
#Feature representation
dim=10

In [20]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')
#Basically here we are passing embedding layer into the rnn with the optimizer as adam optimizer and mse

In [21]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step


array([[[-0.04685127, -0.04468649,  0.04567783, -0.04791641,
          0.03890968, -0.01774172, -0.0255048 , -0.0178455 ,
          0.01032827, -0.00605256],
        [-0.03377222,  0.03963109, -0.03215977,  0.02068702,
          0.02566682, -0.00845208, -0.02731497,  0.04078447,
         -0.04411775,  0.04624819],
        [ 0.04973852, -0.01876905, -0.0073113 ,  0.00152544,
          0.03854985,  0.0469701 ,  0.03403554, -0.02299197,
         -0.02083792,  0.01476676],
        [-0.01341422, -0.03151786, -0.03153676, -0.03322931,
         -0.04024459, -0.0136206 , -0.0485636 ,  0.01043489,
          0.00429283,  0.00312184],
        [-0.00179796, -0.00147368, -0.03801828,  0.03917031,
         -0.02322756,  0.04405794, -0.04276687,  0.04070501,
         -0.02482363, -0.01758821]],

       [[-0.04685127, -0.04468649,  0.04567783, -0.04791641,
          0.03890968, -0.01774172, -0.0255048 , -0.0178455 ,
          0.01032827, -0.00605256],
        [-0.03377222,  0.03963109, -0.03215977,  0

In [23]:
embedded_docs[0]

array([   0, 6764, 8385, 1216, 8467])

In [24]:
"""WE would have list of sentences having diff number of words we want to convert each sentence as list of numbers so each word of sentence is converted to a number basically we will get list of list each list have numbers for each word thats what we formed in embedded docs"""

'WE would have list of sentences having diff number of words we want to convert each sentence as list of numbers so each word of sentence is converted to a number basically we will get list of list each list have numbers for each word thats what we formed in embedded docs'